# numpy assignment

In [1]:
#1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True,8.10.
    #a. Now in the ‘myList’, append these values: 30,40
    #b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [2]:
#1.
mylist=[10,20,30,"apple",True,8.10]
#mylist.append(30,40)
mylist.extend([30,40])

In [3]:
mylist

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [4]:
mylistreverse=mylist.reverse()

In [5]:
mylistreverse

In [6]:
mylist[::-1]

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [7]:
#2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
    #a. After that eliminate the ‘text’ value form the dictonary.
    #b. Add ‘features’ in the dictonary.
    #c. Fetch the ‘data’ element from the dictonary and display it in the output

In [8]:
#2.
d={1:"data",2:"Infomation",3:"text"}
print(d)

{1: 'data', 2: 'Infomation', 3: 'text'}


In [9]:
d.pop(3)

'text'

In [10]:
print(d)

{1: 'data', 2: 'Infomation'}


In [11]:
d[3]="features"

In [12]:
print(d)

{1: 'data', 2: 'Infomation', 3: 'features'}


In [13]:
x=d.get(1)

In [14]:
x

'data'

In [15]:
d[1]

'data'

In [16]:
#3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [17]:
#3.
mytuple=(1,2,3,"apple","mango")
mytuple

(1, 2, 3, 'apple', 'mango')

In [18]:
#4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
    #a. Find the minimum value from the numeric_tuple.
    #b. Concatenate my_tuple with numeric_tuple and store the result in r1.
    #c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [19]:
#4.
ntuple=(10,20,30,40,50)

In [20]:
print(min(ntuple))

10


In [21]:
r1=mytuple+ntuple

In [22]:
print(r1)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [23]:
x=mytuple*2

In [24]:
print(x)

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [25]:
#5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to contains{2,3,7,6,1}
    #a. Perform the below operation:
    #a. set1 union set2
    #b. set1 intersection set2
    #c. set1 difference set2

In [26]:
#5.
set1={1,2,3,4,5}
set2={2,3,7,6,1}
a=set1.union(set2)


In [27]:
print(a)

{1, 2, 3, 4, 5, 6, 7}


In [28]:
b=set1.intersection(set2)

In [29]:
print(b)

{1, 2, 3}


In [30]:
c=set1.difference(set2)
print(c)

{4, 5}


# 2nd file

In [31]:
#1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
#Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
#[
 #[5, 5, 5],
 #[5, 5, 5],
 #[5, 5, 5]
#]


In [32]:
import numpy as np
def abc():
    y=[]
    for i in range(2):
        y.append(int(input()))
    x=tuple(y)
    b=np.full(x,5)
    return b
print(abc())    

3
3
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [33]:
#2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [34]:
##2.:
def add(c,d):
    f=np.add(c,d)
    return f
c=np.array([1,2,3,4,5])
d=np.array([4,5,6,8,9])
print(add(c,d))

[ 5  7  9 12 14]


In [35]:
#3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
#numbers N and M. The method should return the top-left N X M sub matrix e.g:
 #[
 #[1, 2, 3],
 #[4, 5, 6],
 #[7, 8, 9],
 #]
#top_left_sub_matrix (matrix, 2, 2) -> should return:
 #[
 #[1, 2]
 #[4, 5]
 #]

In [36]:
#3.
m=np.array([1,2,3,4,5,6,7,8,9])
x=m.reshape(3,3)

In [37]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
def top_left(m,a,b):
    print(m[:a,:b])
print(top_left(x,2,2))
    

[[1 2]
 [4 5]]
None


In [39]:
#4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
#numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
# [
 #[1, 2, 3],
 #[4, 5, 6],
 #[7, 8, 9],
 #]
#sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
# [
 #[5, 6]
 #[8, 9]
 #]

In [40]:
#4.
def top_left(m,a,b):
    print(m[a:,b:])
print(top_left(x,1,1))



[[5 6]
 [8 9]]
None


In [41]:
#5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
#should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
#standard deviation as values:
# [1, 1, 1]
#solution(arr) -> should return :
# {'mean': 1.0, 'std_dev': 0.0}

In [42]:
#5.
def abc(n):
    a=np.mean(n)
    b=np.std(n)
    d={"mean":a,"std":b}
    return d
n=np.array([7,5,3,1])


In [43]:
print(abc(n))

{'mean': 4.0, 'std': 2.23606797749979}


# 3rd file

In [44]:
#1. Create a 3x3 matrix array with values ranging from 2 to 10

In [45]:
import numpy as np
arr= np.arange(2,11)

print(arr)

ar = arr.reshape((3,3))
ar

[ 2  3  4  5  6  7  8  9 10]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [46]:
#2. Create a numpy array having user input values and convert the integer type to the float type
#of the elements of the array. For instance:
#Original array
#[1, 2, 3, 4]
#Array converted to a float type:
#[ 1. 2. 3. 4.]


In [103]:
import numpy as np
arr1 = []
floatArr = []

array1 =int( input("enter the no."))

for i in range( array1):
    
    arr2  = int(input("enter no  " ))
    arr1.append(arr2)
    
print(arr1)

for n in arr1:
    floatArr.append(float(n))

print(floatArr)



enter the no.5
enter no  3
enter no  4
enter no  6
enter no  7
enter no  8
[3, 4, 6, 7, 8]
[3.0, 4.0, 6.0, 7.0, 8.0]


In [ ]:
#3. Write a Numpy program to append values to the end of an array. For instance:
#Original array:
#[10, 20, 30]
#After append values to the end of the array:
#[10 20 30 40 50 60 70 80 90]

In [82]:
import numpy as np
a = [10,20,30]
a.extend([40,50,60,70,80,90])
print(a)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# 4.Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [91]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
sumarray= np.add(a, b)
sumarray

array([ 5,  7,  9, 11])

In [ ]:
#5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:
    #a. Extract the 1st row from the array.
    #b. Extract the last element from the array.

In [100]:
import numpy as np
s = np.arange(10,91,10)
array1 = s.reshape(3,3)
print(array1)



[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [99]:
array1[2:3,:]

array([[70, 80, 90]])

In [101]:
array1[2:3,2:3]

array([[90]])